wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.13
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1760142114.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.11.13
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
dataset:
  desc: null
  value: spam
lr:
  desc: null
  value: 0.001
opt:
  desc: null
  value: adam
noamp:
  desc: null
  value: false
nowandb:
  desc: null
  value: false
net:
  desc: null
  value: vit
dp:
  desc: null
  value: false
net_ckpt:
  desc: null
  value: ckpts/net_three_fea_nlayer3_nhead4_nblocks4_nhidden512_nembd128_nepochs200_maxfea35_spam_lr1e-3.ckpt
GPT_ckpt:
  desc: null
  value: ckpts/GPT_three_fea_nlayer3_nhead4_nblocks4_nhidden512_nembd128_nepochs200_maxfea35_spam_lr1e-3.ckpt
n_blocks:
  desc: null
  value: 4
n_layer:
  desc: null
  value: 3
n_convs:
  desc: null
  value: 2
n_head:
  desc: null
  value: 4
n_hidden:
  desc: null
  value: 512
n_embd:
  desc: null
  value: 128
max_fea:
  desc: null
  value: 35
max_val_fea:
  desc: null
  value: 20
n_epochs:
  desc: null
  value: 200
init_fea:
  desc: null
  value: 52
second_fea:
  desc: null
  value: 6
third_fea:
  desc: null
  value: 15
wandb_name:
  desc: null
  value: v1_first_stage
wandb_project:
  desc: null
  value: spam
dataset_path:
  desc: null
  value: null
